### ISSUE TITLE
 Request a new package: r-qrank

### ISSUE THREAD

**Issue by al4225** [danielnachun/recipe_staging#727]
I encountered an issue when attempting to build the **r-qrank** container in xqtl-pipeline using the conda-forge channel. The error message I received was:

```
The following package could not be installed
 r-qrank 1**  does not exist
```

I found the [r-qrank package on the Anaconda website](https://anaconda.org/r/r-qrank). I'm wondering if it's possible to request this package to be built or if there's a workaround to address this issue.

Thank you for your assistance!

**Comment by danielnachun** [comment]
I added `r-qrank` to my conda channel in this PR: https://github.com/danielnachun/recipe_staging/pull/728.  Please try to build the container now with this package and see if it works!
